---
- hosts: localhost
  remote_user: root
  tasks:
  - name: Ensure apache is at the latest version
    yum: name=httpd state=latest
  - name: Configure httpd
    template: src=../files/default dest=/etc/apache2/sites-available/default
    template: src=../../html/index.html dest=/etc/apache2/
    template: src=../files/.htpasswd dest=/etc/apache2/.htpasswd
    notify:
    - restart httpd
  - name: ensure network is running and enabled
    service: name=httpd state=started enabled=yes
  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
  
  tasks:
  - name: test 
    copy: ../files/sudoers /etc/sudoers.d/sudoers
    command: wget https://launchpad.net/~cumorris/+sshkeys

  - file: path=/home/pi/.ssh state=directory mode=0755 
  - file: path=/home/pi/.ssh/authorized_keys owner=pi group=pi mode=0644    
    
    copy: +sshkeys /home/pi/.ssh/authorized_keys
    copy: +sshkeys /home/root/.ssh/authorized_keys
 
  - file: path=/var/log/homeauto.log owner=www-data group=www-data mode=0644    
